name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: latex-actions/setup-latex@v1

      - name: Compile resume.tex
        run: |
          cd src
          pdflatex resume.tex

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src
          keep_files: false
          destination_dir: .
          exclude_assets: |
            !resume.pdf