name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile resume.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: src

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src
          keep_files: false
          destination_dir: .
          exclude_assets: |
            !resume.pdf